#!/usr/bin/env bash
# script that returns 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
new_string="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
nstr2="\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$new_string$nstr2/" /etc/nginx/sites-enabled/default
if [ "$(pgrep -c nginx)" -le 0 ]
then
	sudo service nginx start
else
	sudo service nginx restart
fi
